"""f

Revision ID: 1dd5379045bd
Revises: 646ac822db8c
Create Date: 2025-12-11 15:49:49.335372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd5379045bd'
down_revision: Union[str, Sequence[str], None] = '646ac822db8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'book', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'category_id')
    # ### end Alembic commands ###
