"""Update author_genre relations

Revision ID: 53aaee1fe7fa
Revises: 51915c6a9eca
Create Date: 2025-11-28 12:07:39.575249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53aaee1fe7fa'
down_revision: Union[str, Sequence[str], None] = '51915c6a9eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('author_genre_genre_id_fkey'), 'author_genre', type_='foreignkey')
    op.drop_constraint(op.f('author_genre_author_id_fkey'), 'author_genre', type_='foreignkey')
    op.create_foreign_key(None, 'author_genre', 'author', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'author_genre', 'genre', ['genre_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author_genre', type_='foreignkey')
    op.drop_constraint(None, 'author_genre', type_='foreignkey')
    op.create_foreign_key(op.f('author_genre_author_id_fkey'), 'author_genre', 'author', ['author_id'], ['id'])
    op.create_foreign_key(op.f('author_genre_genre_id_fkey'), 'author_genre', 'genre', ['genre_id'], ['id'])
    # ### end Alembic commands ###
