"""Update author_genre FK constraint

Revision ID: 5b2ac9f1250b
Revises: 51915c6a9eca
Create Date: 2025-12-02 01:00:01.610748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2ac9f1250b'
down_revision: Union[str, Sequence[str], None] = '51915c6a9eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uc_author_genre', 'author_genre', ['author_id', 'genre_id'])
    op.drop_constraint(op.f('author_genre_genre_id_fkey'), 'author_genre', type_='foreignkey')
    op.drop_constraint(op.f('author_genre_author_id_fkey'), 'author_genre', type_='foreignkey')
    op.create_foreign_key(None, 'author_genre', 'author', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'author_genre', 'genre', ['genre_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author_genre', type_='foreignkey')
    op.drop_constraint(None, 'author_genre', type_='foreignkey')
    op.create_foreign_key(op.f('author_genre_author_id_fkey'), 'author_genre', 'author', ['author_id'], ['id'])
    op.create_foreign_key(op.f('author_genre_genre_id_fkey'), 'author_genre', 'genre', ['genre_id'], ['id'])
    op.drop_constraint('uc_author_genre', 'author_genre', type_='unique')
    # ### end Alembic commands ###
