"""Author Book table and some fixes

Revision ID: 767620508449
Revises: ef1914cfe917
Create Date: 2025-12-08 17:48:58.661089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '767620508449'
down_revision: Union[str, Sequence[str], None] = 'ef1914cfe917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_book',
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('author_id', 'book_id')
    )
    op.drop_constraint(op.f('uc_author_genre'), 'author_genre', type_='unique')
    op.drop_column('author_genre', 'id')
    op.drop_constraint(op.f('uc_user_book'), 'favorites', type_='unique')
    op.drop_column('favorites', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uc_user_book'), 'favorites', ['user_id', 'book_id'], postgresql_nulls_not_distinct=False)
    op.add_column('author_genre', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uc_author_genre'), 'author_genre', ['author_id', 'genre_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('author_book')
    # ### end Alembic commands ###
