"""removed id from favorites

Revision ID: b6ded31952b7
Revises: c1cf3c4496b1
Create Date: 2025-12-11 10:55:52.624941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ded31952b7'
down_revision: Union[str, Sequence[str], None] = 'c1cf3c4496b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
