"""Drop unique constraint in Author

Revision ID: c0308a91f39c
Revises: da28606709ae
Create Date: 2025-11-15 04:47:01.515626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0308a91f39c'
down_revision: Union[str, Sequence[str], None] = 'da28606709ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('author_first_name_key'), 'author', type_='unique')
    op.drop_constraint(op.f('author_last_name_key'), 'author', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('author_last_name_key'), 'author', ['last_name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('author_first_name_key'), 'author', ['first_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
