"""added favorites base fields

Revision ID: c1cf3c4496b1
Revises: b8b5ae364fe3
Create Date: 2025-12-10 22:25:49.657826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1cf3c4496b1'
down_revision: Union[str, Sequence[str], None] = 'b8b5ae364fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'id')
    # ### end Alembic commands ###
